# label affected logical areas of the repo
"Area: CI":
  - .github/**/*
"Area: RquestBridge backend":
  - app/RquestBridge/**/*
"Area: Rquest Omop Worker":
  - app/rquest-omop-worker/**/*
"Area: Hutch.Relay":
  - app/Hutch.Relay/**/*
"Area: Hutch.Rackit":
  - lib/Hutch.Rackit/**/*
"Area: Website":
  - website/**/*

# label types of changes contained in a PR
"Contains: Migrations":
  - app/**/Migrations/*.cs
