name: hutch-resolve-dev

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  resolve:
    depends_on:
      - db
    image: resolve
    build:
      context: app/resolve
      dockerfile: Dockerfile.cli
