name: Build RquestBridge

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - app/RquestBridge/**
      - test/RquestBridge.Tests/**
      - .github/workflows/build.RquestBridge.yml

env:
  # Configure these
  CI_build-config: release
  CI_dotnet-version: 8.0.x
  CI_project: ./app/RquestBridge/RquestBridge.csproj
  Bridge_test_project: ./test/RquestBridge.Tests/RquestBridge.Tests.csproj

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.CI_dotnet-version }}
      - name: dotnet build
        run: >-
          dotnet build
          ${{ env.CI_project }}
          -c ${{ env.CI_build-config }}
      - name: Run RquestBridge Tests
        run: >-
            dotnet test
            ${{ env.Bridge_test_project }}
            -c ${{ env.CI_build-config }}
