name: Release Hutch.Relay to Docker Hub

on:
  push:
    branches: [main]
    paths:
      - app/Hutch.Relay/**
      - test/Hutch.Relay.Tests/**
      - .github/workflows/release.Hutch.Relay.yml

env:
  namespace: hutchstack
  repo-name: hutch-relay

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set timestamp env var
        run: echo "RUN_TIMESTAMP=$(TZ="Etc/UTC" date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.namespace }}/${{ env.repo-name }}
          tags: |
            ${{ github.sha }}
            ${{ env.RUN_TIMESTAMP }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: app/Hutch.Relay/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
